<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>myrobot_simulation</name>
  <version>0.0.0</version>
  <description>Gazebo launch files and demo nodes for robot arm simulation.</description>
  <maintainer email="robot@todo.todo">robot</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>hand_eye_calibration</exec_depend>
  <exec_depend>visual_grasping_bringup</exec_depend>
  <exec_depend>visual_servo_bringup</exec_depend>
  <exec_depend>graspnet_bringup</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>ros2_aruco</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>visual_perception</exec_depend>
  <exec_depend>myrobot_common</exec_depend>
  <exec_depend>trajectory_retime_server</exec_depend>
  <exec_depend>llm_arm_control</exec_depend>
  <exec_depend>realsense2_gz_description</exec_depend>
  <exec_depend>fairino_arm_moveit_descriptions</exec_depend>
  <exec_depend>myrobot_mpc_avoidance</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>python3-scipy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
